import type { Metadata } from "next";
import Providers from "./providers";
import Navigation from "src/components/navigation/navigation";
import "./globals.scss";
import "../../node_modules/vazirmatn/Vazirmatn-font-face.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Providers>
          <Navigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
